name: Build and Deploy to EKS

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
###
jobs:
  build_and_deploy:

    runs-on: [self-hosted]  # Ensure it runs on your self-hosted GitHub runner

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker (Ensure Docker is installed on your self-hosted runner)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

    
      # Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1
          mask-password: false
          registry-type: private
          skip-logout: false

      # Build Docker image and tag it
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:$GITHUB_SHA .

      # Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:$GITHUB_SHA ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$GITHUB_SHA
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$GITHUB_SHA

    

      # Update kubeconfig for EKS
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      # Deploy the new Docker image to EKS using kubectl
      - name: Deploy to EKS
        run: |
          kubectl set image deployment/${{ secrets.EKS_DEPLOYMENT_NAME }} ${{ secrets.EKS_CONTAINER_NAME }}=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$GITHUB_SHA
          kubectl rollout status deployment/${{ secrets.EKS_DEPLOYMENT_NAME }}

